package de.virtuos.empresa.controller;

import de.virtuos.empresa.model.db.EmpresaUser;
import de.virtuos.empresa.model.db.EmpresaRole;
import de.virtuos.empresa.repository.EmpresaUserRepository;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import javax.annotation.Resource;
import java.util.Set;

@Controller
@RequestMapping(path = "/demo") // This means URL's start with /demo (after Application path)
public class MainController {

    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Resource
    private EmpresaUserRepository empresaUserRepository;

    @PostMapping(path = "/add") // Map ONLY POST Requests
    public @ResponseBody
    String addNewUser(
            @RequestParam String username,
            @RequestParam String password,
            @RequestParam Set<EmpresaRole> roles) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        EmpresaUser n = new EmpresaUser();
        n.setUsername(username);
        n.setPassword(password);
        n.setRoles(roles);
        empresaUserRepository.save(n);
        return "Saved";
    }

    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<EmpresaUser> getAllUsers() {
        // This returns a JSON or XML with the users
        return empresaUserRepository.findAll();
    }

}
